[package]
name = "src"
version = "0.1.0"
authors = ["Dane <dane@lipscombe.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9"
